// Code generated by protoc-gen-go. DO NOT EDIT.
// source: govox.proto

package govox

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Material int32

const (
	Material_AIR          Material = 0
	Material_GRASS        Material = 1
	Material_DIRT         Material = 2
	Material_STONE        Material = 3
	Material_MOON         Material = 4
	Material_ASTEROID     Material = 5
	Material_SUN          Material = 6
	Material_BLUE_BLOCK   Material = 7
	Material_BLUE_SAND    Material = 8
	Material_PURPLE_BLOCK Material = 9
	Material_PURPLE_SAND  Material = 10
	Material_RED_BLOCK    Material = 11
	Material_RED_SAND     Material = 12
	Material_YELLOW_BLOCK Material = 13
	Material_YELLOW_SAND  Material = 14
	Material_WATER        Material = 15
)

var Material_name = map[int32]string{
	0:  "AIR",
	1:  "GRASS",
	2:  "DIRT",
	3:  "STONE",
	4:  "MOON",
	5:  "ASTEROID",
	6:  "SUN",
	7:  "BLUE_BLOCK",
	8:  "BLUE_SAND",
	9:  "PURPLE_BLOCK",
	10: "PURPLE_SAND",
	11: "RED_BLOCK",
	12: "RED_SAND",
	13: "YELLOW_BLOCK",
	14: "YELLOW_SAND",
	15: "WATER",
}

var Material_value = map[string]int32{
	"AIR":          0,
	"GRASS":        1,
	"DIRT":         2,
	"STONE":        3,
	"MOON":         4,
	"ASTEROID":     5,
	"SUN":          6,
	"BLUE_BLOCK":   7,
	"BLUE_SAND":    8,
	"PURPLE_BLOCK": 9,
	"PURPLE_SAND":  10,
	"RED_BLOCK":    11,
	"RED_SAND":     12,
	"YELLOW_BLOCK": 13,
	"YELLOW_SAND":  14,
	"WATER":        15,
}

func (x Material) String() string {
	return proto.EnumName(Material_name, int32(x))
}

func (Material) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_303e99b6bdde8eb4, []int{0}
}

type GetPlanetsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPlanetsRequest) Reset()         { *m = GetPlanetsRequest{} }
func (m *GetPlanetsRequest) String() string { return proto.CompactTextString(m) }
func (*GetPlanetsRequest) ProtoMessage()    {}
func (*GetPlanetsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_303e99b6bdde8eb4, []int{0}
}

func (m *GetPlanetsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPlanetsRequest.Unmarshal(m, b)
}
func (m *GetPlanetsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPlanetsRequest.Marshal(b, m, deterministic)
}
func (m *GetPlanetsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPlanetsRequest.Merge(m, src)
}
func (m *GetPlanetsRequest) XXX_Size() int {
	return xxx_messageInfo_GetPlanetsRequest.Size(m)
}
func (m *GetPlanetsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPlanetsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPlanetsRequest proto.InternalMessageInfo

type GetPlanetsResponse struct {
	Planets              []*PlanetSpec `protobuf:"bytes,1,rep,name=planets,proto3" json:"planets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetPlanetsResponse) Reset()         { *m = GetPlanetsResponse{} }
func (m *GetPlanetsResponse) String() string { return proto.CompactTextString(m) }
func (*GetPlanetsResponse) ProtoMessage()    {}
func (*GetPlanetsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_303e99b6bdde8eb4, []int{1}
}

func (m *GetPlanetsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPlanetsResponse.Unmarshal(m, b)
}
func (m *GetPlanetsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPlanetsResponse.Marshal(b, m, deterministic)
}
func (m *GetPlanetsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPlanetsResponse.Merge(m, src)
}
func (m *GetPlanetsResponse) XXX_Size() int {
	return xxx_messageInfo_GetPlanetsResponse.Size(m)
}
func (m *GetPlanetsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPlanetsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPlanetsResponse proto.InternalMessageInfo

func (m *GetPlanetsResponse) GetPlanets() []*PlanetSpec {
	if m != nil {
		return m.Planets
	}
	return nil
}

type PlanetSpec struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Radius               float64  `protobuf:"fixed64,3,opt,name=radius,proto3" json:"radius,omitempty"`
	AltCells             int64    `protobuf:"varint,4,opt,name=altCells,proto3" json:"altCells,omitempty"`
	OrbitPlanet          int64    `protobuf:"varint,5,opt,name=orbitPlanet,proto3" json:"orbitPlanet,omitempty"`
	OrbitDistance        float64  `protobuf:"fixed64,6,opt,name=orbitDistance,proto3" json:"orbitDistance,omitempty"`
	OrbitSeconds         float64  `protobuf:"fixed64,7,opt,name=orbitSeconds,proto3" json:"orbitSeconds,omitempty"`
	RotationSeconds      float64  `protobuf:"fixed64,8,opt,name=rotationSeconds,proto3" json:"rotationSeconds,omitempty"`
	Seed                 int64    `protobuf:"varint,9,opt,name=seed,proto3" json:"seed,omitempty"`
	GeneratorType        string   `protobuf:"bytes,10,opt,name=generatorType,proto3" json:"generatorType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlanetSpec) Reset()         { *m = PlanetSpec{} }
func (m *PlanetSpec) String() string { return proto.CompactTextString(m) }
func (*PlanetSpec) ProtoMessage()    {}
func (*PlanetSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_303e99b6bdde8eb4, []int{2}
}

func (m *PlanetSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlanetSpec.Unmarshal(m, b)
}
func (m *PlanetSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlanetSpec.Marshal(b, m, deterministic)
}
func (m *PlanetSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlanetSpec.Merge(m, src)
}
func (m *PlanetSpec) XXX_Size() int {
	return xxx_messageInfo_PlanetSpec.Size(m)
}
func (m *PlanetSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_PlanetSpec.DiscardUnknown(m)
}

var xxx_messageInfo_PlanetSpec proto.InternalMessageInfo

func (m *PlanetSpec) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PlanetSpec) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PlanetSpec) GetRadius() float64 {
	if m != nil {
		return m.Radius
	}
	return 0
}

func (m *PlanetSpec) GetAltCells() int64 {
	if m != nil {
		return m.AltCells
	}
	return 0
}

func (m *PlanetSpec) GetOrbitPlanet() int64 {
	if m != nil {
		return m.OrbitPlanet
	}
	return 0
}

func (m *PlanetSpec) GetOrbitDistance() float64 {
	if m != nil {
		return m.OrbitDistance
	}
	return 0
}

func (m *PlanetSpec) GetOrbitSeconds() float64 {
	if m != nil {
		return m.OrbitSeconds
	}
	return 0
}

func (m *PlanetSpec) GetRotationSeconds() float64 {
	if m != nil {
		return m.RotationSeconds
	}
	return 0
}

func (m *PlanetSpec) GetSeed() int64 {
	if m != nil {
		return m.Seed
	}
	return 0
}

func (m *PlanetSpec) GetGeneratorType() string {
	if m != nil {
		return m.GeneratorType
	}
	return ""
}

type GetChunkRequest struct {
	Planet               int64       `protobuf:"varint,1,opt,name=planet,proto3" json:"planet,omitempty"`
	Index                *ChunkIndex `protobuf:"bytes,2,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetChunkRequest) Reset()         { *m = GetChunkRequest{} }
func (m *GetChunkRequest) String() string { return proto.CompactTextString(m) }
func (*GetChunkRequest) ProtoMessage()    {}
func (*GetChunkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_303e99b6bdde8eb4, []int{3}
}

func (m *GetChunkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetChunkRequest.Unmarshal(m, b)
}
func (m *GetChunkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetChunkRequest.Marshal(b, m, deterministic)
}
func (m *GetChunkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetChunkRequest.Merge(m, src)
}
func (m *GetChunkRequest) XXX_Size() int {
	return xxx_messageInfo_GetChunkRequest.Size(m)
}
func (m *GetChunkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetChunkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetChunkRequest proto.InternalMessageInfo

func (m *GetChunkRequest) GetPlanet() int64 {
	if m != nil {
		return m.Planet
	}
	return 0
}

func (m *GetChunkRequest) GetIndex() *ChunkIndex {
	if m != nil {
		return m.Index
	}
	return nil
}

type ChunkIndex struct {
	Lat                  int64    `protobuf:"varint,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon                  int64    `protobuf:"varint,2,opt,name=lon,proto3" json:"lon,omitempty"`
	Alt                  int64    `protobuf:"varint,3,opt,name=alt,proto3" json:"alt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChunkIndex) Reset()         { *m = ChunkIndex{} }
func (m *ChunkIndex) String() string { return proto.CompactTextString(m) }
func (*ChunkIndex) ProtoMessage()    {}
func (*ChunkIndex) Descriptor() ([]byte, []int) {
	return fileDescriptor_303e99b6bdde8eb4, []int{4}
}

func (m *ChunkIndex) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChunkIndex.Unmarshal(m, b)
}
func (m *ChunkIndex) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChunkIndex.Marshal(b, m, deterministic)
}
func (m *ChunkIndex) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChunkIndex.Merge(m, src)
}
func (m *ChunkIndex) XXX_Size() int {
	return xxx_messageInfo_ChunkIndex.Size(m)
}
func (m *ChunkIndex) XXX_DiscardUnknown() {
	xxx_messageInfo_ChunkIndex.DiscardUnknown(m)
}

var xxx_messageInfo_ChunkIndex proto.InternalMessageInfo

func (m *ChunkIndex) GetLat() int64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *ChunkIndex) GetLon() int64 {
	if m != nil {
		return m.Lon
	}
	return 0
}

func (m *ChunkIndex) GetAlt() int64 {
	if m != nil {
		return m.Alt
	}
	return 0
}

type GetChunkResponse struct {
	Chunk                *Chunk   `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetChunkResponse) Reset()         { *m = GetChunkResponse{} }
func (m *GetChunkResponse) String() string { return proto.CompactTextString(m) }
func (*GetChunkResponse) ProtoMessage()    {}
func (*GetChunkResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_303e99b6bdde8eb4, []int{5}
}

func (m *GetChunkResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetChunkResponse.Unmarshal(m, b)
}
func (m *GetChunkResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetChunkResponse.Marshal(b, m, deterministic)
}
func (m *GetChunkResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetChunkResponse.Merge(m, src)
}
func (m *GetChunkResponse) XXX_Size() int {
	return xxx_messageInfo_GetChunkResponse.Size(m)
}
func (m *GetChunkResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetChunkResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetChunkResponse proto.InternalMessageInfo

func (m *GetChunkResponse) GetChunk() *Chunk {
	if m != nil {
		return m.Chunk
	}
	return nil
}

type Chunk struct {
	Cell                 []*Chunk_CellLat `protobuf:"bytes,1,rep,name=cell,proto3" json:"cell,omitempty"`
	WaitingForData       bool             `protobuf:"varint,2,opt,name=waitingForData,proto3" json:"waitingForData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Chunk) Reset()         { *m = Chunk{} }
func (m *Chunk) String() string { return proto.CompactTextString(m) }
func (*Chunk) ProtoMessage()    {}
func (*Chunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_303e99b6bdde8eb4, []int{6}
}

func (m *Chunk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chunk.Unmarshal(m, b)
}
func (m *Chunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chunk.Marshal(b, m, deterministic)
}
func (m *Chunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chunk.Merge(m, src)
}
func (m *Chunk) XXX_Size() int {
	return xxx_messageInfo_Chunk.Size(m)
}
func (m *Chunk) XXX_DiscardUnknown() {
	xxx_messageInfo_Chunk.DiscardUnknown(m)
}

var xxx_messageInfo_Chunk proto.InternalMessageInfo

func (m *Chunk) GetCell() []*Chunk_CellLat {
	if m != nil {
		return m.Cell
	}
	return nil
}

func (m *Chunk) GetWaitingForData() bool {
	if m != nil {
		return m.WaitingForData
	}
	return false
}

type Chunk_CellLat struct {
	Cell                 []*Chunk_CellAlt `protobuf:"bytes,1,rep,name=cell,proto3" json:"cell,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Chunk_CellLat) Reset()         { *m = Chunk_CellLat{} }
func (m *Chunk_CellLat) String() string { return proto.CompactTextString(m) }
func (*Chunk_CellLat) ProtoMessage()    {}
func (*Chunk_CellLat) Descriptor() ([]byte, []int) {
	return fileDescriptor_303e99b6bdde8eb4, []int{6, 0}
}

func (m *Chunk_CellLat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chunk_CellLat.Unmarshal(m, b)
}
func (m *Chunk_CellLat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chunk_CellLat.Marshal(b, m, deterministic)
}
func (m *Chunk_CellLat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chunk_CellLat.Merge(m, src)
}
func (m *Chunk_CellLat) XXX_Size() int {
	return xxx_messageInfo_Chunk_CellLat.Size(m)
}
func (m *Chunk_CellLat) XXX_DiscardUnknown() {
	xxx_messageInfo_Chunk_CellLat.DiscardUnknown(m)
}

var xxx_messageInfo_Chunk_CellLat proto.InternalMessageInfo

func (m *Chunk_CellLat) GetCell() []*Chunk_CellAlt {
	if m != nil {
		return m.Cell
	}
	return nil
}

type Chunk_CellAlt struct {
	Cell                 []*Cell  `protobuf:"bytes,1,rep,name=cell,proto3" json:"cell,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Chunk_CellAlt) Reset()         { *m = Chunk_CellAlt{} }
func (m *Chunk_CellAlt) String() string { return proto.CompactTextString(m) }
func (*Chunk_CellAlt) ProtoMessage()    {}
func (*Chunk_CellAlt) Descriptor() ([]byte, []int) {
	return fileDescriptor_303e99b6bdde8eb4, []int{6, 1}
}

func (m *Chunk_CellAlt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chunk_CellAlt.Unmarshal(m, b)
}
func (m *Chunk_CellAlt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chunk_CellAlt.Marshal(b, m, deterministic)
}
func (m *Chunk_CellAlt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chunk_CellAlt.Merge(m, src)
}
func (m *Chunk_CellAlt) XXX_Size() int {
	return xxx_messageInfo_Chunk_CellAlt.Size(m)
}
func (m *Chunk_CellAlt) XXX_DiscardUnknown() {
	xxx_messageInfo_Chunk_CellAlt.DiscardUnknown(m)
}

var xxx_messageInfo_Chunk_CellAlt proto.InternalMessageInfo

func (m *Chunk_CellAlt) GetCell() []*Cell {
	if m != nil {
		return m.Cell
	}
	return nil
}

type GetPlanetGeometryRequest struct {
	Planet               int64    `protobuf:"varint,1,opt,name=planet,proto3" json:"planet,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPlanetGeometryRequest) Reset()         { *m = GetPlanetGeometryRequest{} }
func (m *GetPlanetGeometryRequest) String() string { return proto.CompactTextString(m) }
func (*GetPlanetGeometryRequest) ProtoMessage()    {}
func (*GetPlanetGeometryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_303e99b6bdde8eb4, []int{7}
}

func (m *GetPlanetGeometryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPlanetGeometryRequest.Unmarshal(m, b)
}
func (m *GetPlanetGeometryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPlanetGeometryRequest.Marshal(b, m, deterministic)
}
func (m *GetPlanetGeometryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPlanetGeometryRequest.Merge(m, src)
}
func (m *GetPlanetGeometryRequest) XXX_Size() int {
	return xxx_messageInfo_GetPlanetGeometryRequest.Size(m)
}
func (m *GetPlanetGeometryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPlanetGeometryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPlanetGeometryRequest proto.InternalMessageInfo

func (m *GetPlanetGeometryRequest) GetPlanet() int64 {
	if m != nil {
		return m.Planet
	}
	return 0
}

type GetPlanetGeometryResponse struct {
	Geometry             *PlanetGeometry `protobuf:"bytes,1,opt,name=geometry,proto3" json:"geometry,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetPlanetGeometryResponse) Reset()         { *m = GetPlanetGeometryResponse{} }
func (m *GetPlanetGeometryResponse) String() string { return proto.CompactTextString(m) }
func (*GetPlanetGeometryResponse) ProtoMessage()    {}
func (*GetPlanetGeometryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_303e99b6bdde8eb4, []int{8}
}

func (m *GetPlanetGeometryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPlanetGeometryResponse.Unmarshal(m, b)
}
func (m *GetPlanetGeometryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPlanetGeometryResponse.Marshal(b, m, deterministic)
}
func (m *GetPlanetGeometryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPlanetGeometryResponse.Merge(m, src)
}
func (m *GetPlanetGeometryResponse) XXX_Size() int {
	return xxx_messageInfo_GetPlanetGeometryResponse.Size(m)
}
func (m *GetPlanetGeometryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPlanetGeometryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPlanetGeometryResponse proto.InternalMessageInfo

func (m *GetPlanetGeometryResponse) GetGeometry() *PlanetGeometry {
	if m != nil {
		return m.Geometry
	}
	return nil
}

type PlanetGeometry struct {
	Altitude             []*PlanetGeometry_AltitudeRow `protobuf:"bytes,1,rep,name=altitude,proto3" json:"altitude,omitempty"`
	Material             []*PlanetGeometry_MaterialRow `protobuf:"bytes,2,rep,name=material,proto3" json:"material,omitempty"`
	IsLoading            bool                          `protobuf:"varint,3,opt,name=isLoading,proto3" json:"isLoading,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *PlanetGeometry) Reset()         { *m = PlanetGeometry{} }
func (m *PlanetGeometry) String() string { return proto.CompactTextString(m) }
func (*PlanetGeometry) ProtoMessage()    {}
func (*PlanetGeometry) Descriptor() ([]byte, []int) {
	return fileDescriptor_303e99b6bdde8eb4, []int{9}
}

func (m *PlanetGeometry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlanetGeometry.Unmarshal(m, b)
}
func (m *PlanetGeometry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlanetGeometry.Marshal(b, m, deterministic)
}
func (m *PlanetGeometry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlanetGeometry.Merge(m, src)
}
func (m *PlanetGeometry) XXX_Size() int {
	return xxx_messageInfo_PlanetGeometry.Size(m)
}
func (m *PlanetGeometry) XXX_DiscardUnknown() {
	xxx_messageInfo_PlanetGeometry.DiscardUnknown(m)
}

var xxx_messageInfo_PlanetGeometry proto.InternalMessageInfo

func (m *PlanetGeometry) GetAltitude() []*PlanetGeometry_AltitudeRow {
	if m != nil {
		return m.Altitude
	}
	return nil
}

func (m *PlanetGeometry) GetMaterial() []*PlanetGeometry_MaterialRow {
	if m != nil {
		return m.Material
	}
	return nil
}

func (m *PlanetGeometry) GetIsLoading() bool {
	if m != nil {
		return m.IsLoading
	}
	return false
}

type PlanetGeometry_AltitudeRow struct {
	Altitude             []int64  `protobuf:"varint,1,rep,packed,name=altitude,proto3" json:"altitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlanetGeometry_AltitudeRow) Reset()         { *m = PlanetGeometry_AltitudeRow{} }
func (m *PlanetGeometry_AltitudeRow) String() string { return proto.CompactTextString(m) }
func (*PlanetGeometry_AltitudeRow) ProtoMessage()    {}
func (*PlanetGeometry_AltitudeRow) Descriptor() ([]byte, []int) {
	return fileDescriptor_303e99b6bdde8eb4, []int{9, 0}
}

func (m *PlanetGeometry_AltitudeRow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlanetGeometry_AltitudeRow.Unmarshal(m, b)
}
func (m *PlanetGeometry_AltitudeRow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlanetGeometry_AltitudeRow.Marshal(b, m, deterministic)
}
func (m *PlanetGeometry_AltitudeRow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlanetGeometry_AltitudeRow.Merge(m, src)
}
func (m *PlanetGeometry_AltitudeRow) XXX_Size() int {
	return xxx_messageInfo_PlanetGeometry_AltitudeRow.Size(m)
}
func (m *PlanetGeometry_AltitudeRow) XXX_DiscardUnknown() {
	xxx_messageInfo_PlanetGeometry_AltitudeRow.DiscardUnknown(m)
}

var xxx_messageInfo_PlanetGeometry_AltitudeRow proto.InternalMessageInfo

func (m *PlanetGeometry_AltitudeRow) GetAltitude() []int64 {
	if m != nil {
		return m.Altitude
	}
	return nil
}

type PlanetGeometry_MaterialRow struct {
	Material             []Material `protobuf:"varint,1,rep,packed,name=material,proto3,enum=govox.Material" json:"material,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PlanetGeometry_MaterialRow) Reset()         { *m = PlanetGeometry_MaterialRow{} }
func (m *PlanetGeometry_MaterialRow) String() string { return proto.CompactTextString(m) }
func (*PlanetGeometry_MaterialRow) ProtoMessage()    {}
func (*PlanetGeometry_MaterialRow) Descriptor() ([]byte, []int) {
	return fileDescriptor_303e99b6bdde8eb4, []int{9, 1}
}

func (m *PlanetGeometry_MaterialRow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlanetGeometry_MaterialRow.Unmarshal(m, b)
}
func (m *PlanetGeometry_MaterialRow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlanetGeometry_MaterialRow.Marshal(b, m, deterministic)
}
func (m *PlanetGeometry_MaterialRow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlanetGeometry_MaterialRow.Merge(m, src)
}
func (m *PlanetGeometry_MaterialRow) XXX_Size() int {
	return xxx_messageInfo_PlanetGeometry_MaterialRow.Size(m)
}
func (m *PlanetGeometry_MaterialRow) XXX_DiscardUnknown() {
	xxx_messageInfo_PlanetGeometry_MaterialRow.DiscardUnknown(m)
}

var xxx_messageInfo_PlanetGeometry_MaterialRow proto.InternalMessageInfo

func (m *PlanetGeometry_MaterialRow) GetMaterial() []Material {
	if m != nil {
		return m.Material
	}
	return nil
}

type SetCellMaterialRequest struct {
	Planet               int64      `protobuf:"varint,1,opt,name=planet,proto3" json:"planet,omitempty"`
	Index                *CellIndex `protobuf:"bytes,2,opt,name=index,proto3" json:"index,omitempty"`
	Cell                 *Cell      `protobuf:"bytes,3,opt,name=cell,proto3" json:"cell,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SetCellMaterialRequest) Reset()         { *m = SetCellMaterialRequest{} }
func (m *SetCellMaterialRequest) String() string { return proto.CompactTextString(m) }
func (*SetCellMaterialRequest) ProtoMessage()    {}
func (*SetCellMaterialRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_303e99b6bdde8eb4, []int{10}
}

func (m *SetCellMaterialRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetCellMaterialRequest.Unmarshal(m, b)
}
func (m *SetCellMaterialRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetCellMaterialRequest.Marshal(b, m, deterministic)
}
func (m *SetCellMaterialRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetCellMaterialRequest.Merge(m, src)
}
func (m *SetCellMaterialRequest) XXX_Size() int {
	return xxx_messageInfo_SetCellMaterialRequest.Size(m)
}
func (m *SetCellMaterialRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetCellMaterialRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetCellMaterialRequest proto.InternalMessageInfo

func (m *SetCellMaterialRequest) GetPlanet() int64 {
	if m != nil {
		return m.Planet
	}
	return 0
}

func (m *SetCellMaterialRequest) GetIndex() *CellIndex {
	if m != nil {
		return m.Index
	}
	return nil
}

func (m *SetCellMaterialRequest) GetCell() *Cell {
	if m != nil {
		return m.Cell
	}
	return nil
}

type Cell struct {
	Material             Material `protobuf:"varint,1,opt,name=material,proto3,enum=govox.Material" json:"material,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cell) Reset()         { *m = Cell{} }
func (m *Cell) String() string { return proto.CompactTextString(m) }
func (*Cell) ProtoMessage()    {}
func (*Cell) Descriptor() ([]byte, []int) {
	return fileDescriptor_303e99b6bdde8eb4, []int{11}
}

func (m *Cell) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cell.Unmarshal(m, b)
}
func (m *Cell) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cell.Marshal(b, m, deterministic)
}
func (m *Cell) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cell.Merge(m, src)
}
func (m *Cell) XXX_Size() int {
	return xxx_messageInfo_Cell.Size(m)
}
func (m *Cell) XXX_DiscardUnknown() {
	xxx_messageInfo_Cell.DiscardUnknown(m)
}

var xxx_messageInfo_Cell proto.InternalMessageInfo

func (m *Cell) GetMaterial() Material {
	if m != nil {
		return m.Material
	}
	return Material_AIR
}

type CellIndex struct {
	Lat                  int64    `protobuf:"varint,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon                  int64    `protobuf:"varint,2,opt,name=lon,proto3" json:"lon,omitempty"`
	Alt                  int64    `protobuf:"varint,3,opt,name=alt,proto3" json:"alt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CellIndex) Reset()         { *m = CellIndex{} }
func (m *CellIndex) String() string { return proto.CompactTextString(m) }
func (*CellIndex) ProtoMessage()    {}
func (*CellIndex) Descriptor() ([]byte, []int) {
	return fileDescriptor_303e99b6bdde8eb4, []int{12}
}

func (m *CellIndex) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CellIndex.Unmarshal(m, b)
}
func (m *CellIndex) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CellIndex.Marshal(b, m, deterministic)
}
func (m *CellIndex) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CellIndex.Merge(m, src)
}
func (m *CellIndex) XXX_Size() int {
	return xxx_messageInfo_CellIndex.Size(m)
}
func (m *CellIndex) XXX_DiscardUnknown() {
	xxx_messageInfo_CellIndex.DiscardUnknown(m)
}

var xxx_messageInfo_CellIndex proto.InternalMessageInfo

func (m *CellIndex) GetLat() int64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *CellIndex) GetLon() int64 {
	if m != nil {
		return m.Lon
	}
	return 0
}

func (m *CellIndex) GetAlt() int64 {
	if m != nil {
		return m.Alt
	}
	return 0
}

type CellLoc struct {
	Lat                  float64  `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon                  float64  `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"`
	Alt                  float64  `protobuf:"fixed64,3,opt,name=alt,proto3" json:"alt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CellLoc) Reset()         { *m = CellLoc{} }
func (m *CellLoc) String() string { return proto.CompactTextString(m) }
func (*CellLoc) ProtoMessage()    {}
func (*CellLoc) Descriptor() ([]byte, []int) {
	return fileDescriptor_303e99b6bdde8eb4, []int{13}
}

func (m *CellLoc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CellLoc.Unmarshal(m, b)
}
func (m *CellLoc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CellLoc.Marshal(b, m, deterministic)
}
func (m *CellLoc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CellLoc.Merge(m, src)
}
func (m *CellLoc) XXX_Size() int {
	return xxx_messageInfo_CellLoc.Size(m)
}
func (m *CellLoc) XXX_DiscardUnknown() {
	xxx_messageInfo_CellLoc.DiscardUnknown(m)
}

var xxx_messageInfo_CellLoc proto.InternalMessageInfo

func (m *CellLoc) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *CellLoc) GetLon() float64 {
	if m != nil {
		return m.Lon
	}
	return 0
}

func (m *CellLoc) GetAlt() float64 {
	if m != nil {
		return m.Alt
	}
	return 0
}

type SetCellMaterialResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetCellMaterialResponse) Reset()         { *m = SetCellMaterialResponse{} }
func (m *SetCellMaterialResponse) String() string { return proto.CompactTextString(m) }
func (*SetCellMaterialResponse) ProtoMessage()    {}
func (*SetCellMaterialResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_303e99b6bdde8eb4, []int{14}
}

func (m *SetCellMaterialResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetCellMaterialResponse.Unmarshal(m, b)
}
func (m *SetCellMaterialResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetCellMaterialResponse.Marshal(b, m, deterministic)
}
func (m *SetCellMaterialResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetCellMaterialResponse.Merge(m, src)
}
func (m *SetCellMaterialResponse) XXX_Size() int {
	return xxx_messageInfo_SetCellMaterialResponse.Size(m)
}
func (m *SetCellMaterialResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetCellMaterialResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetCellMaterialResponse proto.InternalMessageInfo

type SendTextRequest struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendTextRequest) Reset()         { *m = SendTextRequest{} }
func (m *SendTextRequest) String() string { return proto.CompactTextString(m) }
func (*SendTextRequest) ProtoMessage()    {}
func (*SendTextRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_303e99b6bdde8eb4, []int{15}
}

func (m *SendTextRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendTextRequest.Unmarshal(m, b)
}
func (m *SendTextRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendTextRequest.Marshal(b, m, deterministic)
}
func (m *SendTextRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendTextRequest.Merge(m, src)
}
func (m *SendTextRequest) XXX_Size() int {
	return xxx_messageInfo_SendTextRequest.Size(m)
}
func (m *SendTextRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendTextRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendTextRequest proto.InternalMessageInfo

func (m *SendTextRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type SendTextResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendTextResponse) Reset()         { *m = SendTextResponse{} }
func (m *SendTextResponse) String() string { return proto.CompactTextString(m) }
func (*SendTextResponse) ProtoMessage()    {}
func (*SendTextResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_303e99b6bdde8eb4, []int{16}
}

func (m *SendTextResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendTextResponse.Unmarshal(m, b)
}
func (m *SendTextResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendTextResponse.Marshal(b, m, deterministic)
}
func (m *SendTextResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendTextResponse.Merge(m, src)
}
func (m *SendTextResponse) XXX_Size() int {
	return xxx_messageInfo_SendTextResponse.Size(m)
}
func (m *SendTextResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendTextResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendTextResponse proto.InternalMessageInfo

type UpdatePlayerStateRequest struct {
	Name                 string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Position             []float64 `protobuf:"fixed64,2,rep,packed,name=position,proto3" json:"position,omitempty"`
	LookDir              []float64 `protobuf:"fixed64,3,rep,packed,name=lookDir,proto3" json:"lookDir,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UpdatePlayerStateRequest) Reset()         { *m = UpdatePlayerStateRequest{} }
func (m *UpdatePlayerStateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePlayerStateRequest) ProtoMessage()    {}
func (*UpdatePlayerStateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_303e99b6bdde8eb4, []int{17}
}

func (m *UpdatePlayerStateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePlayerStateRequest.Unmarshal(m, b)
}
func (m *UpdatePlayerStateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePlayerStateRequest.Marshal(b, m, deterministic)
}
func (m *UpdatePlayerStateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePlayerStateRequest.Merge(m, src)
}
func (m *UpdatePlayerStateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePlayerStateRequest.Size(m)
}
func (m *UpdatePlayerStateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePlayerStateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePlayerStateRequest proto.InternalMessageInfo

func (m *UpdatePlayerStateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdatePlayerStateRequest) GetPosition() []float64 {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *UpdatePlayerStateRequest) GetLookDir() []float64 {
	if m != nil {
		return m.LookDir
	}
	return nil
}

type UpdatePlayerStateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePlayerStateResponse) Reset()         { *m = UpdatePlayerStateResponse{} }
func (m *UpdatePlayerStateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdatePlayerStateResponse) ProtoMessage()    {}
func (*UpdatePlayerStateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_303e99b6bdde8eb4, []int{18}
}

func (m *UpdatePlayerStateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePlayerStateResponse.Unmarshal(m, b)
}
func (m *UpdatePlayerStateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePlayerStateResponse.Marshal(b, m, deterministic)
}
func (m *UpdatePlayerStateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePlayerStateResponse.Merge(m, src)
}
func (m *UpdatePlayerStateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdatePlayerStateResponse.Size(m)
}
func (m *UpdatePlayerStateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePlayerStateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePlayerStateResponse proto.InternalMessageInfo

type HitPlayerRequest struct {
	From                 string   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Target               string   `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Amount               int64    `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HitPlayerRequest) Reset()         { *m = HitPlayerRequest{} }
func (m *HitPlayerRequest) String() string { return proto.CompactTextString(m) }
func (*HitPlayerRequest) ProtoMessage()    {}
func (*HitPlayerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_303e99b6bdde8eb4, []int{19}
}

func (m *HitPlayerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HitPlayerRequest.Unmarshal(m, b)
}
func (m *HitPlayerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HitPlayerRequest.Marshal(b, m, deterministic)
}
func (m *HitPlayerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HitPlayerRequest.Merge(m, src)
}
func (m *HitPlayerRequest) XXX_Size() int {
	return xxx_messageInfo_HitPlayerRequest.Size(m)
}
func (m *HitPlayerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HitPlayerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HitPlayerRequest proto.InternalMessageInfo

func (m *HitPlayerRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *HitPlayerRequest) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *HitPlayerRequest) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type HitPlayerResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HitPlayerResponse) Reset()         { *m = HitPlayerResponse{} }
func (m *HitPlayerResponse) String() string { return proto.CompactTextString(m) }
func (*HitPlayerResponse) ProtoMessage()    {}
func (*HitPlayerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_303e99b6bdde8eb4, []int{20}
}

func (m *HitPlayerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HitPlayerResponse.Unmarshal(m, b)
}
func (m *HitPlayerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HitPlayerResponse.Marshal(b, m, deterministic)
}
func (m *HitPlayerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HitPlayerResponse.Merge(m, src)
}
func (m *HitPlayerResponse) XXX_Size() int {
	return xxx_messageInfo_HitPlayerResponse.Size(m)
}
func (m *HitPlayerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HitPlayerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HitPlayerResponse proto.InternalMessageInfo

type CellMaterialRequest struct {
	Index                *CellIndex  `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	Planet               *PlanetSpec `protobuf:"bytes,2,opt,name=planet,proto3" json:"planet,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CellMaterialRequest) Reset()         { *m = CellMaterialRequest{} }
func (m *CellMaterialRequest) String() string { return proto.CompactTextString(m) }
func (*CellMaterialRequest) ProtoMessage()    {}
func (*CellMaterialRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_303e99b6bdde8eb4, []int{21}
}

func (m *CellMaterialRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CellMaterialRequest.Unmarshal(m, b)
}
func (m *CellMaterialRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CellMaterialRequest.Marshal(b, m, deterministic)
}
func (m *CellMaterialRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CellMaterialRequest.Merge(m, src)
}
func (m *CellMaterialRequest) XXX_Size() int {
	return xxx_messageInfo_CellMaterialRequest.Size(m)
}
func (m *CellMaterialRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CellMaterialRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CellMaterialRequest proto.InternalMessageInfo

func (m *CellMaterialRequest) GetIndex() *CellIndex {
	if m != nil {
		return m.Index
	}
	return nil
}

func (m *CellMaterialRequest) GetPlanet() *PlanetSpec {
	if m != nil {
		return m.Planet
	}
	return nil
}

type CellMaterialResponse struct {
	Cell                 *Cell    `protobuf:"bytes,1,opt,name=cell,proto3" json:"cell,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CellMaterialResponse) Reset()         { *m = CellMaterialResponse{} }
func (m *CellMaterialResponse) String() string { return proto.CompactTextString(m) }
func (*CellMaterialResponse) ProtoMessage()    {}
func (*CellMaterialResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_303e99b6bdde8eb4, []int{22}
}

func (m *CellMaterialResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CellMaterialResponse.Unmarshal(m, b)
}
func (m *CellMaterialResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CellMaterialResponse.Marshal(b, m, deterministic)
}
func (m *CellMaterialResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CellMaterialResponse.Merge(m, src)
}
func (m *CellMaterialResponse) XXX_Size() int {
	return xxx_messageInfo_CellMaterialResponse.Size(m)
}
func (m *CellMaterialResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CellMaterialResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CellMaterialResponse proto.InternalMessageInfo

func (m *CellMaterialResponse) GetCell() *Cell {
	if m != nil {
		return m.Cell
	}
	return nil
}

func init() {
	proto.RegisterEnum("govox.Material", Material_name, Material_value)
	proto.RegisterType((*GetPlanetsRequest)(nil), "govox.GetPlanetsRequest")
	proto.RegisterType((*GetPlanetsResponse)(nil), "govox.GetPlanetsResponse")
	proto.RegisterType((*PlanetSpec)(nil), "govox.PlanetSpec")
	proto.RegisterType((*GetChunkRequest)(nil), "govox.GetChunkRequest")
	proto.RegisterType((*ChunkIndex)(nil), "govox.ChunkIndex")
	proto.RegisterType((*GetChunkResponse)(nil), "govox.GetChunkResponse")
	proto.RegisterType((*Chunk)(nil), "govox.Chunk")
	proto.RegisterType((*Chunk_CellLat)(nil), "govox.Chunk.CellLat")
	proto.RegisterType((*Chunk_CellAlt)(nil), "govox.Chunk.CellAlt")
	proto.RegisterType((*GetPlanetGeometryRequest)(nil), "govox.GetPlanetGeometryRequest")
	proto.RegisterType((*GetPlanetGeometryResponse)(nil), "govox.GetPlanetGeometryResponse")
	proto.RegisterType((*PlanetGeometry)(nil), "govox.PlanetGeometry")
	proto.RegisterType((*PlanetGeometry_AltitudeRow)(nil), "govox.PlanetGeometry.AltitudeRow")
	proto.RegisterType((*PlanetGeometry_MaterialRow)(nil), "govox.PlanetGeometry.MaterialRow")
	proto.RegisterType((*SetCellMaterialRequest)(nil), "govox.SetCellMaterialRequest")
	proto.RegisterType((*Cell)(nil), "govox.Cell")
	proto.RegisterType((*CellIndex)(nil), "govox.CellIndex")
	proto.RegisterType((*CellLoc)(nil), "govox.CellLoc")
	proto.RegisterType((*SetCellMaterialResponse)(nil), "govox.SetCellMaterialResponse")
	proto.RegisterType((*SendTextRequest)(nil), "govox.SendTextRequest")
	proto.RegisterType((*SendTextResponse)(nil), "govox.SendTextResponse")
	proto.RegisterType((*UpdatePlayerStateRequest)(nil), "govox.UpdatePlayerStateRequest")
	proto.RegisterType((*UpdatePlayerStateResponse)(nil), "govox.UpdatePlayerStateResponse")
	proto.RegisterType((*HitPlayerRequest)(nil), "govox.HitPlayerRequest")
	proto.RegisterType((*HitPlayerResponse)(nil), "govox.HitPlayerResponse")
	proto.RegisterType((*CellMaterialRequest)(nil), "govox.CellMaterialRequest")
	proto.RegisterType((*CellMaterialResponse)(nil), "govox.CellMaterialResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GovoxClient is the client API for Govox service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GovoxClient interface {
	GetPlanets(ctx context.Context, in *GetPlanetsRequest, opts ...grpc.CallOption) (*GetPlanetsResponse, error)
	GetChunk(ctx context.Context, in *GetChunkRequest, opts ...grpc.CallOption) (*GetChunkResponse, error)
	GetPlanetGeometry(ctx context.Context, in *GetPlanetGeometryRequest, opts ...grpc.CallOption) (*GetPlanetGeometryResponse, error)
	SetCellMaterial(ctx context.Context, in *SetCellMaterialRequest, opts ...grpc.CallOption) (*SetCellMaterialResponse, error)
	SendText(ctx context.Context, in *SendTextRequest, opts ...grpc.CallOption) (*SendTextResponse, error)
	UpdatePlayerState(ctx context.Context, in *UpdatePlayerStateRequest, opts ...grpc.CallOption) (*UpdatePlayerStateResponse, error)
	HitPlayer(ctx context.Context, in *HitPlayerRequest, opts ...grpc.CallOption) (*HitPlayerResponse, error)
}

type govoxClient struct {
	cc *grpc.ClientConn
}

func NewGovoxClient(cc *grpc.ClientConn) GovoxClient {
	return &govoxClient{cc}
}

func (c *govoxClient) GetPlanets(ctx context.Context, in *GetPlanetsRequest, opts ...grpc.CallOption) (*GetPlanetsResponse, error) {
	out := new(GetPlanetsResponse)
	err := c.cc.Invoke(ctx, "/govox.Govox/GetPlanets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *govoxClient) GetChunk(ctx context.Context, in *GetChunkRequest, opts ...grpc.CallOption) (*GetChunkResponse, error) {
	out := new(GetChunkResponse)
	err := c.cc.Invoke(ctx, "/govox.Govox/GetChunk", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *govoxClient) GetPlanetGeometry(ctx context.Context, in *GetPlanetGeometryRequest, opts ...grpc.CallOption) (*GetPlanetGeometryResponse, error) {
	out := new(GetPlanetGeometryResponse)
	err := c.cc.Invoke(ctx, "/govox.Govox/GetPlanetGeometry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *govoxClient) SetCellMaterial(ctx context.Context, in *SetCellMaterialRequest, opts ...grpc.CallOption) (*SetCellMaterialResponse, error) {
	out := new(SetCellMaterialResponse)
	err := c.cc.Invoke(ctx, "/govox.Govox/SetCellMaterial", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *govoxClient) SendText(ctx context.Context, in *SendTextRequest, opts ...grpc.CallOption) (*SendTextResponse, error) {
	out := new(SendTextResponse)
	err := c.cc.Invoke(ctx, "/govox.Govox/SendText", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *govoxClient) UpdatePlayerState(ctx context.Context, in *UpdatePlayerStateRequest, opts ...grpc.CallOption) (*UpdatePlayerStateResponse, error) {
	out := new(UpdatePlayerStateResponse)
	err := c.cc.Invoke(ctx, "/govox.Govox/UpdatePlayerState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *govoxClient) HitPlayer(ctx context.Context, in *HitPlayerRequest, opts ...grpc.CallOption) (*HitPlayerResponse, error) {
	out := new(HitPlayerResponse)
	err := c.cc.Invoke(ctx, "/govox.Govox/HitPlayer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GovoxServer is the server API for Govox service.
type GovoxServer interface {
	GetPlanets(context.Context, *GetPlanetsRequest) (*GetPlanetsResponse, error)
	GetChunk(context.Context, *GetChunkRequest) (*GetChunkResponse, error)
	GetPlanetGeometry(context.Context, *GetPlanetGeometryRequest) (*GetPlanetGeometryResponse, error)
	SetCellMaterial(context.Context, *SetCellMaterialRequest) (*SetCellMaterialResponse, error)
	SendText(context.Context, *SendTextRequest) (*SendTextResponse, error)
	UpdatePlayerState(context.Context, *UpdatePlayerStateRequest) (*UpdatePlayerStateResponse, error)
	HitPlayer(context.Context, *HitPlayerRequest) (*HitPlayerResponse, error)
}

func RegisterGovoxServer(s *grpc.Server, srv GovoxServer) {
	s.RegisterService(&_Govox_serviceDesc, srv)
}

func _Govox_GetPlanets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlanetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GovoxServer).GetPlanets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/govox.Govox/GetPlanets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GovoxServer).GetPlanets(ctx, req.(*GetPlanetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Govox_GetChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GovoxServer).GetChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/govox.Govox/GetChunk",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GovoxServer).GetChunk(ctx, req.(*GetChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Govox_GetPlanetGeometry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlanetGeometryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GovoxServer).GetPlanetGeometry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/govox.Govox/GetPlanetGeometry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GovoxServer).GetPlanetGeometry(ctx, req.(*GetPlanetGeometryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Govox_SetCellMaterial_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetCellMaterialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GovoxServer).SetCellMaterial(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/govox.Govox/SetCellMaterial",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GovoxServer).SetCellMaterial(ctx, req.(*SetCellMaterialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Govox_SendText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GovoxServer).SendText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/govox.Govox/SendText",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GovoxServer).SendText(ctx, req.(*SendTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Govox_UpdatePlayerState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePlayerStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GovoxServer).UpdatePlayerState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/govox.Govox/UpdatePlayerState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GovoxServer).UpdatePlayerState(ctx, req.(*UpdatePlayerStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Govox_HitPlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HitPlayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GovoxServer).HitPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/govox.Govox/HitPlayer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GovoxServer).HitPlayer(ctx, req.(*HitPlayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Govox_serviceDesc = grpc.ServiceDesc{
	ServiceName: "govox.Govox",
	HandlerType: (*GovoxServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPlanets",
			Handler:    _Govox_GetPlanets_Handler,
		},
		{
			MethodName: "GetChunk",
			Handler:    _Govox_GetChunk_Handler,
		},
		{
			MethodName: "GetPlanetGeometry",
			Handler:    _Govox_GetPlanetGeometry_Handler,
		},
		{
			MethodName: "SetCellMaterial",
			Handler:    _Govox_SetCellMaterial_Handler,
		},
		{
			MethodName: "SendText",
			Handler:    _Govox_SendText_Handler,
		},
		{
			MethodName: "UpdatePlayerState",
			Handler:    _Govox_UpdatePlayerState_Handler,
		},
		{
			MethodName: "HitPlayer",
			Handler:    _Govox_HitPlayer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "govox.proto",
}

// GeneratorClient is the client API for Generator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GeneratorClient interface {
	CellMaterial(ctx context.Context, in *CellMaterialRequest, opts ...grpc.CallOption) (*CellMaterialResponse, error)
}

type generatorClient struct {
	cc *grpc.ClientConn
}

func NewGeneratorClient(cc *grpc.ClientConn) GeneratorClient {
	return &generatorClient{cc}
}

func (c *generatorClient) CellMaterial(ctx context.Context, in *CellMaterialRequest, opts ...grpc.CallOption) (*CellMaterialResponse, error) {
	out := new(CellMaterialResponse)
	err := c.cc.Invoke(ctx, "/govox.Generator/CellMaterial", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GeneratorServer is the server API for Generator service.
type GeneratorServer interface {
	CellMaterial(context.Context, *CellMaterialRequest) (*CellMaterialResponse, error)
}

func RegisterGeneratorServer(s *grpc.Server, srv GeneratorServer) {
	s.RegisterService(&_Generator_serviceDesc, srv)
}

func _Generator_CellMaterial_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CellMaterialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeneratorServer).CellMaterial(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/govox.Generator/CellMaterial",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeneratorServer).CellMaterial(ctx, req.(*CellMaterialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Generator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "govox.Generator",
	HandlerType: (*GeneratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CellMaterial",
			Handler:    _Generator_CellMaterial_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "govox.proto",
}

func init() { proto.RegisterFile("govox.proto", fileDescriptor_303e99b6bdde8eb4) }

var fileDescriptor_303e99b6bdde8eb4 = []byte{
	// 1090 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0x6f, 0x6f, 0xdb, 0x36,
	0x13, 0x8f, 0xfc, 0x27, 0xb6, 0xcf, 0x8e, 0xad, 0xb2, 0x7d, 0x52, 0x45, 0x7d, 0xb6, 0x7a, 0xc2,
	0xd6, 0xb9, 0x2d, 0x10, 0x60, 0x0e, 0xb0, 0x01, 0x03, 0x86, 0xcd, 0x89, 0x3d, 0x2f, 0x98, 0x1b,
	0x07, 0x94, 0xd3, 0x6e, 0xaf, 0x06, 0xd6, 0xe2, 0x5c, 0xa1, 0x8a, 0xe8, 0x49, 0xcc, 0x9a, 0x7c,
	0x8e, 0xed, 0xa3, 0xec, 0xd5, 0xbe, 0xcd, 0xbe, 0xc9, 0x40, 0x8a, 0xa2, 0x69, 0x5b, 0x49, 0x80,
	0xbd, 0xe3, 0xfd, 0xee, 0x77, 0xc7, 0xe3, 0xf1, 0xee, 0x48, 0x68, 0x2e, 0xd8, 0xef, 0xec, 0xfa,
	0x70, 0x99, 0x30, 0xce, 0x50, 0x55, 0x0a, 0xde, 0x43, 0x78, 0x30, 0xa6, 0xfc, 0x3c, 0x22, 0x31,
	0xe5, 0x29, 0xa6, 0xbf, 0x5d, 0xd1, 0x94, 0x7b, 0x03, 0x40, 0x26, 0x98, 0x2e, 0x59, 0x9c, 0x52,
	0xf4, 0x12, 0x6a, 0xcb, 0x0c, 0x72, 0xac, 0x6e, 0xb9, 0xd7, 0xec, 0x3f, 0x38, 0xcc, 0x1c, 0x66,
	0x44, 0x7f, 0x49, 0xe7, 0x38, 0x67, 0x78, 0x7f, 0x95, 0x00, 0x56, 0x38, 0x6a, 0x43, 0x29, 0x0c,
	0x1c, 0xab, 0x6b, 0xf5, 0xca, 0xb8, 0x14, 0x06, 0x08, 0x41, 0x25, 0x26, 0x97, 0xd4, 0x29, 0x75,
	0xad, 0x5e, 0x03, 0xcb, 0x35, 0xda, 0x87, 0xdd, 0x84, 0x04, 0xe1, 0x55, 0xea, 0x94, 0xbb, 0x56,
	0xcf, 0xc2, 0x4a, 0x42, 0x2e, 0xd4, 0x49, 0xc4, 0x4f, 0x68, 0x14, 0xa5, 0x4e, 0x45, 0x7a, 0xd0,
	0x32, 0xea, 0x42, 0x93, 0x25, 0x6f, 0x43, 0x15, 0xab, 0x53, 0x95, 0x6a, 0x13, 0x42, 0x9f, 0xc2,
	0x9e, 0x14, 0x87, 0x61, 0xca, 0x49, 0x3c, 0xa7, 0xce, 0xae, 0x74, 0xbe, 0x0e, 0x22, 0x0f, 0x5a,
	0x12, 0xf0, 0xe9, 0x9c, 0xc5, 0x41, 0xea, 0xd4, 0x24, 0x69, 0x0d, 0x43, 0x3d, 0xe8, 0x24, 0x8c,
	0x13, 0x1e, 0xb2, 0x38, 0xa7, 0xd5, 0x25, 0x6d, 0x13, 0x16, 0xa7, 0x4b, 0x29, 0x0d, 0x9c, 0x86,
	0x0c, 0x47, 0xae, 0x45, 0x1c, 0x0b, 0x1a, 0xd3, 0x84, 0x70, 0x96, 0xcc, 0x6e, 0x96, 0xd4, 0x01,
	0x79, 0xf4, 0x75, 0xd0, 0xc3, 0xd0, 0x19, 0x53, 0x7e, 0xf2, 0xee, 0x2a, 0x7e, 0xaf, 0x2e, 0x43,
	0xa4, 0x25, 0x4b, 0xaa, 0x4a, 0x9f, 0x92, 0xd0, 0xe7, 0x50, 0x0d, 0xe3, 0x80, 0x5e, 0xcb, 0x1c,
	0xae, 0x2e, 0x43, 0xda, 0x9e, 0x0a, 0x05, 0xce, 0xf4, 0xde, 0x31, 0xc0, 0x0a, 0x44, 0x36, 0x94,
	0x23, 0x92, 0xfb, 0x12, 0x4b, 0x89, 0xb0, 0x58, 0xba, 0x11, 0x08, 0x8b, 0x05, 0x42, 0x22, 0x2e,
	0xaf, 0xa1, 0x8c, 0xc5, 0xd2, 0xfb, 0x12, 0xec, 0x55, 0x5c, 0xaa, 0x1e, 0x3c, 0xa8, 0xce, 0x05,
	0x20, 0x7d, 0x35, 0xfb, 0x2d, 0x33, 0x00, 0x9c, 0xa9, 0xbc, 0xbf, 0x2d, 0xa8, 0x4a, 0x00, 0xf5,
	0xa0, 0x32, 0xa7, 0x51, 0xa4, 0x4a, 0xe7, 0x91, 0x49, 0x3e, 0x14, 0x77, 0x39, 0x21, 0x1c, 0x4b,
	0x06, 0x7a, 0x06, 0xed, 0x0f, 0x24, 0xe4, 0x61, 0xbc, 0xf8, 0x9e, 0x25, 0x43, 0xc2, 0x89, 0x0c,
	0xad, 0x8e, 0x37, 0x50, 0xf7, 0x08, 0x6a, 0xca, 0xf0, 0x5e, 0xe7, 0x83, 0x48, 0x39, 0x77, 0x5f,
	0x64, 0x46, 0x83, 0x88, 0xa3, 0xa7, 0x6b, 0x46, 0xcd, 0xdc, 0x88, 0x46, 0x51, 0xc6, 0xf5, 0xfa,
	0xe0, 0xe8, 0x36, 0x18, 0x53, 0x76, 0x49, 0x79, 0x72, 0x73, 0xcf, 0xad, 0x78, 0x67, 0x70, 0x50,
	0x60, 0xa3, 0x32, 0xf6, 0x05, 0xd4, 0x17, 0x0a, 0x53, 0x49, 0xfb, 0xdf, 0x5a, 0x0b, 0x69, 0x03,
	0x4d, 0xf3, 0xfe, 0x28, 0x41, 0x7b, 0x5d, 0x89, 0xbe, 0x91, 0xfd, 0x10, 0xf2, 0xab, 0x80, 0xaa,
	0xd8, 0x3f, 0x29, 0xf4, 0x72, 0x38, 0x50, 0x2c, 0xcc, 0x3e, 0x60, 0x6d, 0x22, 0xcc, 0x2f, 0x09,
	0xa7, 0x49, 0x48, 0x22, 0xa7, 0x74, 0x97, 0xf9, 0x2b, 0xc5, 0x92, 0xe6, 0xb9, 0x09, 0xfa, 0x3f,
	0x34, 0xc2, 0x74, 0xc2, 0x48, 0x10, 0xc6, 0x0b, 0x59, 0x21, 0x75, 0xbc, 0x02, 0xdc, 0xe7, 0xd0,
	0x34, 0x76, 0x55, 0xad, 0xbb, 0x0a, 0xb5, 0xbc, 0x8a, 0xc3, 0xfd, 0x1a, 0x9a, 0xc6, 0x0e, 0xe8,
	0xa5, 0x11, 0x96, 0xa0, 0xb6, 0xfb, 0x1d, 0x15, 0x96, 0x66, 0x69, 0x82, 0x77, 0x03, 0xfb, 0x3e,
	0x95, 0x23, 0x40, 0x2b, 0xef, 0xe9, 0x96, 0x67, 0xeb, 0xdd, 0x62, 0x1b, 0xb7, 0x6d, 0x36, 0x8b,
	0x2e, 0x8a, 0xb2, 0xa4, 0x15, 0x14, 0xc5, 0x11, 0x54, 0x84, 0xb4, 0x11, 0xaf, 0x75, 0x77, 0xbc,
	0x03, 0x68, 0xe8, 0x9d, 0xfe, 0x63, 0x07, 0x7e, 0xab, 0xaa, 0x9d, 0xcd, 0x4d, 0x07, 0xd6, 0x96,
	0x03, 0x6b, 0xcb, 0x81, 0x95, 0x39, 0x38, 0x80, 0xc7, 0x5b, 0x39, 0xcb, 0xea, 0xd2, 0xfb, 0x0c,
	0x3a, 0x3e, 0x8d, 0x83, 0x19, 0xbd, 0xe6, 0x79, 0x1e, 0x11, 0x54, 0x38, 0xbd, 0xce, 0x36, 0x69,
	0x60, 0xb9, 0xf6, 0x10, 0xd8, 0x2b, 0x9a, 0x32, 0x0d, 0xc0, 0xb9, 0x58, 0x06, 0x84, 0xd3, 0xf3,
	0x88, 0xdc, 0xd0, 0xc4, 0xe7, 0x84, 0x53, 0xc3, 0x87, 0x1c, 0xf2, 0x96, 0x31, 0xe4, 0x5d, 0xa8,
	0x2f, 0x59, 0x1a, 0x8a, 0x69, 0x29, 0xab, 0xcf, 0xc2, 0x5a, 0x46, 0x0e, 0xd4, 0x22, 0xc6, 0xde,
	0x0f, 0xc3, 0xc4, 0x29, 0x4b, 0x55, 0x2e, 0x7a, 0x4f, 0xe0, 0xa0, 0x60, 0x17, 0x15, 0xc2, 0x6b,
	0xb0, 0x7f, 0x90, 0xe3, 0xfe, 0x86, 0x26, 0xc6, 0xd6, 0xbf, 0x26, 0xec, 0x32, 0xdf, 0x5a, 0xac,
	0x45, 0x69, 0x70, 0x92, 0x2c, 0x28, 0x57, 0xaf, 0x8e, 0x92, 0x04, 0x4e, 0x2e, 0xd9, 0x55, 0x9c,
	0xa7, 0x5b, 0x49, 0xe2, 0x69, 0x34, 0xfc, 0xaa, 0xcd, 0xde, 0xc1, 0xc3, 0xa2, 0xb2, 0xd3, 0xe5,
	0x65, 0xdd, 0x5d, 0x5e, 0xcf, 0x75, 0x79, 0xae, 0x4f, 0x6d, 0xe3, 0x09, 0xcd, 0x27, 0xc9, 0x57,
	0xf0, 0xa8, 0xe8, 0xb2, 0x8c, 0xb1, 0x55, 0x5c, 0xa1, 0x2f, 0xfe, 0xb1, 0xa0, 0x9e, 0x5b, 0xa1,
	0x1a, 0x94, 0x07, 0xa7, 0xd8, 0xde, 0x41, 0x0d, 0xa8, 0x8e, 0xf1, 0xc0, 0xf7, 0x6d, 0x0b, 0xd5,
	0xa1, 0x32, 0x3c, 0xc5, 0x33, 0xbb, 0x24, 0x40, 0x7f, 0x36, 0x3d, 0x1b, 0xd9, 0x65, 0x01, 0xbe,
	0x9a, 0x4e, 0xcf, 0xec, 0x0a, 0x6a, 0x41, 0x7d, 0xe0, 0xcf, 0x46, 0x78, 0x7a, 0x3a, 0xb4, 0xab,
	0xc2, 0x81, 0x7f, 0x71, 0x66, 0xef, 0xa2, 0x36, 0xc0, 0xf1, 0xe4, 0x62, 0xf4, 0xcb, 0xf1, 0x64,
	0x7a, 0xf2, 0xa3, 0x5d, 0x43, 0x7b, 0xd0, 0x90, 0xb2, 0x3f, 0x38, 0x1b, 0xda, 0x75, 0x64, 0x43,
	0xeb, 0xfc, 0x02, 0x9f, 0x4f, 0x72, 0x42, 0x03, 0x75, 0xa0, 0xa9, 0x10, 0x49, 0x01, 0x61, 0x81,
	0x47, 0x43, 0xa5, 0x6f, 0x8a, 0x7d, 0x84, 0x28, 0x95, 0x2d, 0x61, 0xff, 0xf3, 0x68, 0x32, 0x99,
	0xbe, 0x51, 0xfa, 0x3d, 0x61, 0xaf, 0x10, 0x49, 0x69, 0x8b, 0x68, 0xdf, 0x0c, 0x66, 0x23, 0x6c,
	0x77, 0xfa, 0x7f, 0x56, 0xa0, 0x3a, 0x16, 0x07, 0x47, 0x27, 0x00, 0xab, 0xbf, 0x0a, 0x72, 0x54,
	0x3a, 0xb6, 0xfe, 0x34, 0xee, 0x41, 0x81, 0x46, 0xdd, 0xe9, 0x8e, 0x98, 0x89, 0xf9, 0xf3, 0x86,
	0xf6, 0x57, 0x44, 0xf3, 0x1d, 0x76, 0x1f, 0x6f, 0xe1, 0xda, 0xfc, 0x27, 0xe3, 0x13, 0xa5, 0xc7,
	0xf4, 0xd3, 0xcd, 0x0d, 0x37, 0x9e, 0x10, 0xb7, 0x7b, 0x3b, 0x41, 0x7b, 0xc6, 0xa2, 0x33, 0xd7,
	0x9a, 0x16, 0x7d, 0xa4, 0xcc, 0x8a, 0x07, 0xa0, 0xfb, 0xf1, 0x6d, 0x6a, 0xf3, 0xb0, 0x79, 0x1b,
	0xeb, 0xc3, 0x6e, 0xb4, 0xbf, 0x3e, 0xec, 0x56, 0xbf, 0xcb, 0xc3, 0x6e, 0xf5, 0xa2, 0x3e, 0xec,
	0x6d, 0xb3, 0x40, 0x1f, 0xf6, 0xf6, 0x36, 0xde, 0x41, 0xdf, 0x41, 0x43, 0x37, 0x1c, 0xca, 0x23,
	0xd8, 0x6c, 0x6d, 0xd7, 0xd9, 0x56, 0xe4, 0x1e, 0xfa, 0xaf, 0xa1, 0x31, 0xce, 0xff, 0x53, 0xe8,
	0x14, 0x5a, 0x6b, 0x89, 0x73, 0x8d, 0x56, 0xd9, 0xcc, 0xda, 0x93, 0x42, 0x5d, 0xee, 0xf7, 0xed,
	0xae, 0xfc, 0x33, 0x1f, 0xfd, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xe6, 0x6c, 0x6d, 0x44, 0x42, 0x0b,
	0x00, 0x00,
}
