# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import govox_pb2 as govox__pb2


class GovoxStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetPlanets = channel.unary_unary(
        '/govox.Govox/GetPlanets',
        request_serializer=govox__pb2.GetPlanetsRequest.SerializeToString,
        response_deserializer=govox__pb2.GetPlanetsResponse.FromString,
        )
    self.GetChunk = channel.unary_unary(
        '/govox.Govox/GetChunk',
        request_serializer=govox__pb2.GetChunkRequest.SerializeToString,
        response_deserializer=govox__pb2.GetChunkResponse.FromString,
        )
    self.GetPlanetGeometry = channel.unary_unary(
        '/govox.Govox/GetPlanetGeometry',
        request_serializer=govox__pb2.GetPlanetGeometryRequest.SerializeToString,
        response_deserializer=govox__pb2.GetPlanetGeometryResponse.FromString,
        )
    self.SetCellMaterial = channel.unary_unary(
        '/govox.Govox/SetCellMaterial',
        request_serializer=govox__pb2.SetCellMaterialRequest.SerializeToString,
        response_deserializer=govox__pb2.SetCellMaterialResponse.FromString,
        )
    self.SendText = channel.unary_unary(
        '/govox.Govox/SendText',
        request_serializer=govox__pb2.SendTextRequest.SerializeToString,
        response_deserializer=govox__pb2.SendTextResponse.FromString,
        )
    self.UpdatePlayerState = channel.unary_unary(
        '/govox.Govox/UpdatePlayerState',
        request_serializer=govox__pb2.UpdatePlayerStateRequest.SerializeToString,
        response_deserializer=govox__pb2.UpdatePlayerStateResponse.FromString,
        )
    self.HitPlayer = channel.unary_unary(
        '/govox.Govox/HitPlayer',
        request_serializer=govox__pb2.HitPlayerRequest.SerializeToString,
        response_deserializer=govox__pb2.HitPlayerResponse.FromString,
        )


class GovoxServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetPlanets(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetChunk(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPlanetGeometry(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetCellMaterial(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendText(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdatePlayerState(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def HitPlayer(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GovoxServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetPlanets': grpc.unary_unary_rpc_method_handler(
          servicer.GetPlanets,
          request_deserializer=govox__pb2.GetPlanetsRequest.FromString,
          response_serializer=govox__pb2.GetPlanetsResponse.SerializeToString,
      ),
      'GetChunk': grpc.unary_unary_rpc_method_handler(
          servicer.GetChunk,
          request_deserializer=govox__pb2.GetChunkRequest.FromString,
          response_serializer=govox__pb2.GetChunkResponse.SerializeToString,
      ),
      'GetPlanetGeometry': grpc.unary_unary_rpc_method_handler(
          servicer.GetPlanetGeometry,
          request_deserializer=govox__pb2.GetPlanetGeometryRequest.FromString,
          response_serializer=govox__pb2.GetPlanetGeometryResponse.SerializeToString,
      ),
      'SetCellMaterial': grpc.unary_unary_rpc_method_handler(
          servicer.SetCellMaterial,
          request_deserializer=govox__pb2.SetCellMaterialRequest.FromString,
          response_serializer=govox__pb2.SetCellMaterialResponse.SerializeToString,
      ),
      'SendText': grpc.unary_unary_rpc_method_handler(
          servicer.SendText,
          request_deserializer=govox__pb2.SendTextRequest.FromString,
          response_serializer=govox__pb2.SendTextResponse.SerializeToString,
      ),
      'UpdatePlayerState': grpc.unary_unary_rpc_method_handler(
          servicer.UpdatePlayerState,
          request_deserializer=govox__pb2.UpdatePlayerStateRequest.FromString,
          response_serializer=govox__pb2.UpdatePlayerStateResponse.SerializeToString,
      ),
      'HitPlayer': grpc.unary_unary_rpc_method_handler(
          servicer.HitPlayer,
          request_deserializer=govox__pb2.HitPlayerRequest.FromString,
          response_serializer=govox__pb2.HitPlayerResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'govox.Govox', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class GeneratorStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CellMaterial = channel.unary_unary(
        '/govox.Generator/CellMaterial',
        request_serializer=govox__pb2.CellMaterialRequest.SerializeToString,
        response_deserializer=govox__pb2.CellMaterialResponse.FromString,
        )


class GeneratorServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CellMaterial(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GeneratorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CellMaterial': grpc.unary_unary_rpc_method_handler(
          servicer.CellMaterial,
          request_deserializer=govox__pb2.CellMaterialRequest.FromString,
          response_serializer=govox__pb2.CellMaterialResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'govox.Generator', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
